In [1]:
A={'score' : [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]}
A

{'score': [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]}

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.DataFrame(A)

In [4]:
df

score
0       3
1       5
2       7
3       2
4       8
5      10
6      11
7      65
8      72
9      81
10     99
11    100
12    150

In [5]:
B=df.rolling(window=3).mean()

In [6]:
B

score
0          NaN
1          NaN
2     5.000000
3     4.666667
4     5.666667
5     6.666667
6     9.666667
7    28.666667
8    49.333333
9    72.666667
10   84.000000
11   93.333333
12  116.333333

In [3]:
import numpy as np

In [6]:
np.array(l)
def moving_avg(l,k,n):
    MA=n-k+1
    l1=[]
    i=0
    while i < MA:
        a=l[i:i+k]
        w=sum(a)/k
        l1.append(w)
        i=i+1
    print(l1)
moving_avg([12,14,13,12,14,17,18,15],3,8)    

[13.0, 13.0, 13.0, 14.333333333333334, 16.333333333333332, 16.666666666666668]


In [2]:
import numpy as np

l=[]

n= int(input("number of items in an array"))

for i in range(0,n):
    num=int(input("numbers"))
    l.append(num)

print("list is :",l)

arr=np.array(l)
print("Array:",arr)

def matrix():

    m=np.vander(arr,N=4)
    print("the required matrix is :",m)
matrix()    


number of items in an array4
numbers4
numbers2
numbers1
numbers3
list is : [4, 2, 1, 3]
Array: [4 2 1 3]
the required matrix is : [[64 16  4  1]
 [ 8  4  2  1]
 [ 1  1  1  1]
 [27  9  3  1]]
